import { internalMutation } from "../_generated/server";
import type { Infer } from "convex/values";
import {
  areaHotel,
  nivelBasico,
  nivelIngles,
  tipoContenido,
  tipoFrase,
} from "../schema";

type NivelCefr = Infer<typeof nivelIngles>;
type NivelCurso = Infer<typeof nivelBasico>;
type Area = Infer<typeof areaHotel>;
type TipoVocabulario = Infer<typeof tipoContenido>;
type TipoFrase = Infer<typeof tipoFrase>;

type PalabraSemilla = {
  textoIngles: string;
  traduccionEspanol: string;
  ejemploIngles: string;
  nivel: NivelCefr;
  nivelBasico: NivelCurso;
  area: Area;
  tipo: TipoVocabulario;
  categoria: string;
};

type FraseSemilla = {
  textoIngles: string;
  traduccionEspanol: string;
  nivel: NivelCefr;
  nivelBasico: NivelCurso;
  area: Area;
  tipo: TipoFrase;
  categoria: string;
};

const ETIQUETAS_POR_CATEGORIA: Record<string, string[]> = {
  saludos: ["saludo", "cortesia"],
  "frases basicas": ["recepcion", "cortesia"],
  comprension: ["comprension", "cortesia"],
  direcciones: ["direccion", "ubicacion"],
  recepcion: ["recepcion", "atencion"],
  preguntas: ["pregunta", "recepcion"],
  respuestas: ["respuesta", "recepcion"],
  instrucciones: ["instruccion", "direccion"],
  aclaraciones: ["aclaracion", "comprension"],
  lugares: ["hotel", "lugar"],
  verbos: ["verbo", "instruccion"],
  ubicacion: ["ubicacion", "direccion"],
};

const PALABRAS: PalabraSemilla[] = [
  {
    textoIngles: "Hotel",
    traduccionEspanol: "Hotel",
    ejemploIngles: "The hotel is on your left.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Reception",
    traduccionEspanol: "Recepción",
    ejemploIngles: "Reception is straight ahead.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Front desk",
    traduccionEspanol: "Recepción",
    ejemploIngles: "The front desk is in the lobby.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Entrance",
    traduccionEspanol: "Entrada",
    ejemploIngles: "The entrance is on the left.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Exit",
    traduccionEspanol: "Salida",
    ejemploIngles: "The exit is behind you.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Building",
    traduccionEspanol: "Edificio",
    ejemploIngles: "Reception is the first building on your left.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Road",
    traduccionEspanol: "Camino",
    ejemploIngles: "Continue down this road.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Gate",
    traduccionEspanol: "Portón / entrada",
    ejemploIngles: "The gate is in front of you.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Parking",
    traduccionEspanol: "Estacionamiento",
    ejemploIngles: "Parking is behind the building.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Guest",
    traduccionEspanol: "Huésped",
    ejemploIngles: "Are you a guest at the hotel?",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Room",
    traduccionEspanol: "Habitación",
    ejemploIngles: "Your room is on the right.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Restaurant",
    traduccionEspanol: "Restaurante",
    ejemploIngles: "The restaurant is next to the lobby.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Left",
    traduccionEspanol: "Izquierda",
    ejemploIngles: "Turn left at the gate.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Right",
    traduccionEspanol: "Derecha",
    ejemploIngles: "Turn right after the gate.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Straight",
    traduccionEspanol: "Recto",
    ejemploIngles: "Go straight for 200 meters.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Ahead",
    traduccionEspanol: "Adelante",
    ejemploIngles: "The entrance is ahead.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Here",
    traduccionEspanol: "Aquí",
    ejemploIngles: "Turn left here.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "There",
    traduccionEspanol: "Allí",
    ejemploIngles: "Reception is over there.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "First",
    traduccionEspanol: "Primero",
    ejemploIngles: "Reception is the first building on your left.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Meters",
    traduccionEspanol: "Metros",
    ejemploIngles: "It is about 200 meters.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "direcciones",
  },
  {
    textoIngles: "Go",
    traduccionEspanol: "Ir / vaya",
    ejemploIngles: "Go straight ahead.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "verbos",
  },
  {
    textoIngles: "Continue",
    traduccionEspanol: "Continuar / continúe",
    ejemploIngles: "Continue straight for 200 meters.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "verbos",
  },
  {
    textoIngles: "Turn",
    traduccionEspanol: "Girar / gire",
    ejemploIngles: "Turn right here.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "verbos",
  },
  {
    textoIngles: "Walk",
    traduccionEspanol: "Caminar / camine",
    ejemploIngles: "You can walk from here.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "verbos",
  },
  {
    textoIngles: "Stop",
    traduccionEspanol: "Detenerse / pare",
    ejemploIngles: "Stop at the gate.",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "palabra",
    categoria: "verbos",
  },
  {
    textoIngles: "Security",
    traduccionEspanol: "Seguridad",
    ejemploIngles: "Security is at the entrance.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Security guard",
    traduccionEspanol: "Guarda de seguridad",
    ejemploIngles: "The security guard is at the gate.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Main building",
    traduccionEspanol: "Edificio principal",
    ejemploIngles: "The main building is straight ahead.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "First building",
    traduccionEspanol: "Primer edificio",
    ejemploIngles: "Reception is the first building on your left.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Parking lot",
    traduccionEspanol: "Estacionamiento",
    ejemploIngles: "The parking lot is on your right.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Lobby",
    traduccionEspanol: "Vestíbulo / lobby",
    ejemploIngles: "The lobby is next to reception.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Reservation",
    traduccionEspanol: "Reservación",
    ejemploIngles: "Do you have a reservation?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Car",
    traduccionEspanol: "Automóvil",
    ejemploIngles: "You can drive your car.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Taxi",
    traduccionEspanol: "Taxi",
    ejemploIngles: "The taxi is in front of the hotel.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Shuttle",
    traduccionEspanol: "Transporte del hotel",
    ejemploIngles: "Take the shuttle to the hotel.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Door",
    traduccionEspanol: "Puerta",
    ejemploIngles: "Enter through the door on the left.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Side",
    traduccionEspanol: "Lado",
    ejemploIngles: "The entrance is on the left side.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "Intersection",
    traduccionEspanol: "Cruce / intersección",
    ejemploIngles: "Continue until you reach the intersection.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "lugares",
  },
  {
    textoIngles: "On your left",
    traduccionEspanol: "A su izquierda",
    ejemploIngles: "Reception is on your left.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "On your right",
    traduccionEspanol: "A su derecha",
    ejemploIngles: "The parking lot is on your right.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "In front of",
    traduccionEspanol: "En frente de",
    ejemploIngles: "The hotel is in front of you.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Behind",
    traduccionEspanol: "Detrás de",
    ejemploIngles: "Parking is behind the building.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Next to",
    traduccionEspanol: "Al lado de",
    ejemploIngles: "The restaurant is next to the lobby.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Before",
    traduccionEspanol: "Antes de",
    ejemploIngles: "Turn left before the gate.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "After",
    traduccionEspanol: "Después de",
    ejemploIngles: "Turn right after the intersection.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Straight ahead",
    traduccionEspanol: "Justo adelante",
    ejemploIngles: "Reception is straight ahead.",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Across from",
    traduccionEspanol: "En frente de",
    ejemploIngles: "Reception is across from the parking lot.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Until",
    traduccionEspanol: "Hasta",
    ejemploIngles: "Go straight until the intersection.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Reach",
    traduccionEspanol: "Llegar a",
    ejemploIngles: "Continue until you reach the intersection.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Through",
    traduccionEspanol: "Por / a través de",
    ejemploIngles: "Enter through the door on the left.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Around",
    traduccionEspanol: "Alrededor de",
    ejemploIngles: "Parking is around the building.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Approximately",
    traduccionEspanol: "Aproximadamente",
    ejemploIngles: "It is approximately 200 meters.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "palabra",
    categoria: "ubicacion",
  },
  {
    textoIngles: "Main entrance",
    traduccionEspanol: "Entrada principal",
    ejemploIngles: "The main entrance is on the right.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Left side",
    traduccionEspanol: "Lado izquierdo",
    ejemploIngles: "The entrance is on the left side.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
  {
    textoIngles: "Right side",
    traduccionEspanol: "Lado derecho",
    ejemploIngles: "The restaurant is on the right side.",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "lugares",
  },
];

const FRASES: FraseSemilla[] = [
  {
    textoIngles: "Hello",
    traduccionEspanol: "Hola",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "Good morning",
    traduccionEspanol: "Buenos días",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "Good afternoon",
    traduccionEspanol: "Buenas tardes",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "Good evening",
    traduccionEspanol: "Buenas noches",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "Welcome",
    traduccionEspanol: "Bienvenido/a",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "Welcome to the hotel",
    traduccionEspanol: "Bienvenido/a al hotel",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "frase",
    categoria: "saludos",
  },
  {
    textoIngles: "Thank you",
    traduccionEspanol: "Gracias",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "You're welcome",
    traduccionEspanol: "Con gusto / De nada",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "saludos",
  },
  {
    textoIngles: "How can I help you?",
    traduccionEspanol: "¿Cómo puedo ayudarle?",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Reception?",
    traduccionEspanol: "¿Recepción?",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "expresion",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Go straight",
    traduccionEspanol: "Siga recto",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Go straight ahead",
    traduccionEspanol: "Siga hacia adelante",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Turn left",
    traduccionEspanol: "Gire a la izquierda",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Turn right",
    traduccionEspanol: "Gire a la derecha",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "It's on your left",
    traduccionEspanol: "Está a su izquierda",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "It's on your right",
    traduccionEspanol: "Está a su derecha",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Reception is on your left",
    traduccionEspanol: "Recepción está a su izquierda",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Reception is on your right",
    traduccionEspanol: "Recepción está a su derecha",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Reception is straight ahead",
    traduccionEspanol: "Recepción está justo adelante",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "frases basicas",
  },
  {
    textoIngles: "About 200 meters",
    traduccionEspanol: "Aproximadamente 200 metros",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "expresion",
    categoria: "frases basicas",
  },
  {
    textoIngles: "Sorry?",
    traduccionEspanol: "¿Disculpe?",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "comprension",
  },
  {
    textoIngles: "Excuse me?",
    traduccionEspanol: "¿Disculpe?",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "comprension",
  },
  {
    textoIngles: "Please, say that again",
    traduccionEspanol: "Por favor, dígalo otra vez",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles: "Could you repeat, please?",
    traduccionEspanol: "¿Podría repetir, por favor?",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles: "Slowly, please",
    traduccionEspanol: "Más despacio, por favor",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "expresion",
    categoria: "comprension",
  },
  {
    textoIngles: "I don't understand",
    traduccionEspanol: "No entiendo",
    nivel: "A1",
    nivelBasico: 1,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles:
      "Go straight for 200 meters. Reception is on your left",
    traduccionEspanol:
      "Siga recto 200 metros. Recepción está a su izquierda",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Go straight for about 200 meters. Reception is the first building on your left",
    traduccionEspanol:
      "Siga recto aproximadamente 200 metros. Recepción es el primer edificio a su izquierda",
    nivel: "A1",
    nivelBasico: 1,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles: "Can I help you?",
    traduccionEspanol: "¿Puedo ayudarle?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "recepcion",
  },
  {
    textoIngles: "Are you looking for reception?",
    traduccionEspanol: "¿Está buscando recepción?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "recepcion",
  },
  {
    textoIngles: "Are you going to reception?",
    traduccionEspanol: "¿Va hacia recepción?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "recepcion",
  },
  {
    textoIngles: "Are you a guest at the hotel?",
    traduccionEspanol: "¿Es huésped del hotel?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "recepcion",
  },
  {
    textoIngles: "Do you have a reservation?",
    traduccionEspanol: "¿Tiene una reservación?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "recepcion",
  },
  {
    textoIngles: "Continue straight",
    traduccionEspanol: "Continúe recto",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles: "Keep going straight",
    traduccionEspanol: "Continúe derecho",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles: "Continue down this road",
    traduccionEspanol: "Continúe por este camino",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Go straight for about 200 meters. The first building on your left is reception",
    traduccionEspanol:
      "Siga recto aproximadamente 200 metros. El primer edificio a su izquierda es recepción",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Continue straight for about 200 meters. Reception will be on your left",
    traduccionEspanol:
      "Continúe recto aproximadamente 200 metros. Recepción estará a su izquierda",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Keep going straight. Reception is the first building on your left",
    traduccionEspanol:
      "Continúe recto. Recepción es el primer edificio a su izquierda",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Go straight ahead for about 200 meters. You'll see reception on your left",
    traduccionEspanol:
      "Siga adelante aproximadamente 200 metros. Verá recepción a su izquierda",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles: "Where is reception?",
    traduccionEspanol: "¿Dónde está recepción?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Where is the front desk?",
    traduccionEspanol: "¿Dónde está recepción?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Where should I go?",
    traduccionEspanol: "¿Adónde debo ir?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Is it on the left?",
    traduccionEspanol: "¿Está a la izquierda?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Is it on the right?",
    traduccionEspanol: "¿Está a la derecha?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Do I go straight?",
    traduccionEspanol: "¿Sigo recto?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Is it far?",
    traduccionEspanol: "¿Está lejos?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Can I walk there?",
    traduccionEspanol: "¿Puedo ir caminando?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Can I drive there?",
    traduccionEspanol: "¿Puedo ir en automóvil?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Where can I park?",
    traduccionEspanol: "¿Dónde puedo estacionar?",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "preguntas",
  },
  {
    textoIngles: "Yes, go straight",
    traduccionEspanol: "Sí, siga recto",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "Yes, on your left",
    traduccionEspanol: "Sí, a su izquierda",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "Yes, on your right",
    traduccionEspanol: "Sí, a su derecha",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "No, turn left here",
    traduccionEspanol: "No, gire a la izquierda aquí",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "It's very close",
    traduccionEspanol: "Está muy cerca",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "It's about 200 meters",
    traduccionEspanol: "Está aproximadamente a 200 metros",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "You can walk",
    traduccionEspanol: "Puede ir caminando",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "You can drive",
    traduccionEspanol: "Puede ir en automóvil",
    nivel: "A2",
    nivelBasico: 2,
    area: "guarda",
    tipo: "frase",
    categoria: "respuestas",
  },
  {
    textoIngles: "Until you reach the intersection",
    traduccionEspanol: "Hasta que llegue al cruce",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "Until you get to the intersection",
    traduccionEspanol: "Hasta que llegue al cruce",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "You will see a building in front of you",
    traduccionEspanol: "Verá un edificio en frente de usted",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "You'll see a building straight ahead",
    traduccionEspanol: "Verá un edificio justo adelante",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "That building is reception",
    traduccionEspanol: "Ese edificio es recepción",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "The entrance is on the left side",
    traduccionEspanol: "La entrada está en el lado izquierdo",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "Enter through the door on the left",
    traduccionEspanol: "Ingrese por la puerta de la izquierda",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles: "Go in through the entrance on your left",
    traduccionEspanol: "Ingrese por la entrada que está a su izquierda",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "instrucciones",
  },
  {
    textoIngles:
      "Go straight until the intersection. Reception is the building in front of you. The entrance is on the left",
    traduccionEspanol:
      "Siga recto hasta el cruce. Recepción es el edificio que está en frente de usted. La entrada está a la izquierda",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Continue straight until you reach the intersection. You will see a building in front of you. That is reception. Use the entrance on the left",
    traduccionEspanol:
      "Continúe recto hasta llegar al cruce. Verá un edificio en frente de usted. Ese es recepción. Use la entrada de la izquierda",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles:
      "Keep going until you get to the intersection. Reception will be straight ahead. Enter through the entrance on the left side of the building",
    traduccionEspanol:
      "Continúe hasta llegar al cruce. Recepción estará justo adelante. Ingrese por la entrada del lado izquierdo del edificio",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "direcciones",
  },
  {
    textoIngles: "Do you mean reception?",
    traduccionEspanol: "¿Se refiere a recepción?",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "aclaraciones",
  },
  {
    textoIngles: "The front desk?",
    traduccionEspanol: "¿La recepción?",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "aclaraciones",
  },
  {
    textoIngles: "The restaurant?",
    traduccionEspanol: "¿El restaurante?",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "aclaraciones",
  },
  {
    textoIngles: "The parking lot?",
    traduccionEspanol: "¿El estacionamiento?",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "expresion",
    categoria: "aclaraciones",
  },
  {
    textoIngles: "Do you mean the main building?",
    traduccionEspanol: "¿Se refiere al edificio principal?",
    nivel: "B1",
    nivelBasico: 3,
    area: "guarda",
    tipo: "frase",
    categoria: "aclaraciones",
  },
  {
    textoIngles: "I'm sorry, I didn't understand",
    traduccionEspanol: "Lo siento, no entendí",
    nivel: "B1",
    nivelBasico: 3,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles: "Could you repeat that, please?",
    traduccionEspanol: "¿Podría repetir eso, por favor?",
    nivel: "B1",
    nivelBasico: 3,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles: "Can you say that again, please?",
    traduccionEspanol: "¿Puede decirlo otra vez, por favor?",
    nivel: "B1",
    nivelBasico: 3,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
  {
    textoIngles: "Could you speak more slowly, please?",
    traduccionEspanol: "¿Podría hablar más despacio, por favor?",
    nivel: "B1",
    nivelBasico: 3,
    area: "general",
    tipo: "frase",
    categoria: "comprension",
  },
];

export const cargarVocabularioBasico = internalMutation({
  args: {},
  handler: async (ctx) => {
    const ahora = Date.now();
    const resumen = {
      palabrasInsertadas: 0,
      frasesInsertadas: 0,
      palabrasOmitidas: 0,
      frasesOmitidas: 0,
    };

    for (const palabra of PALABRAS) {
      const existente = await ctx.db
        .query("vocabulario")
        .withIndex("por_texto_ingles", (q) =>
          q.eq("textoIngles", palabra.textoIngles)
        )
        .unique();
      if (existente !== null) {
        resumen.palabrasOmitidas += 1;
        continue;
      }
      await ctx.db.insert("vocabulario", {
        ...palabra,
        etiquetas: ETIQUETAS_POR_CATEGORIA[palabra.categoria] ?? [],
        activo: true,
        creadoEn: ahora,
        actualizadoEn: ahora,
      });
      resumen.palabrasInsertadas += 1;
    }

    for (const frase of FRASES) {
      const existente = await ctx.db
        .query("frases")
        .withIndex("por_texto_ingles", (q) =>
          q.eq("textoIngles", frase.textoIngles)
        )
        .unique();
      if (existente !== null) {
        resumen.frasesOmitidas += 1;
        continue;
      }
      await ctx.db.insert("frases", {
        ...frase,
        etiquetas: ETIQUETAS_POR_CATEGORIA[frase.categoria] ?? [],
        activo: true,
        creadoEn: ahora,
        actualizadoEn: ahora,
      });
      resumen.frasesInsertadas += 1;
    }

    return resumen;
  },
});
